### ISSUE TITLE
请问该如何使用？

### ISSUE THREAD

**Issue by ShadowPikaqiu** [0rigina1/chunyu#1]
我直接打开文件运行 报错
    self._startSign(user['userName'], user['userPwd'])
  File "E:\chunyu-main\autoSign.py", line 34, in _startSign
    csrfToken = self._getCsrfToken()
  File "E:\chunyu-main\autoSign.py", line 40, in _getCsrfToken
    soup = BeautifulSoup(req.text, 'lxml')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\bs4\__init__.py", line 245, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by 0rigina1** [comment]
## 缺少lxml模块
#### 以下是两种解决方法，任意一种都可以解决
1、安装lxml模块
```bash
pip install lxml
```
2、修改html解析器
```python
# autoSing.py

40| soup = BeautifulSoup(req.text, 'lxml')
# 修改为
40| soup = BeautifulSoup(req.text, 'html.parser')
```

**Comment by ShadowPikaqiu** [comment]
> 

感谢 可以签到了

**Comment by ShadowPikaqiu** [comment]
这个可以直接上传到云函数吗？我上传到云函数测试失败了
START RequestId: 4a06bd2b-cc86-4791-a874-16f8938fc3dd

Init Report RequestId: 4a06bd2b-cc86-4791-a874-16f8938fc3dd Coldstart: 417ms (PullCode: 232ms InitRuntime: 7ms InitFunction: 178ms) Memory: 128MB MemUsage: 7.82MB

ERROR RequestId: 4a06bd2b-cc86-4791-a874-16f8938fc3dd Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python37/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python37/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python37/lib/python3.7/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python37/lib/python3.7/imp.py", line 171, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 696, in _load   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 728, in exec_module   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed   File "/var/user/index.py", line 11, in <module>     import requests ModuleNotFoundError: No module named 'requests'", "statusCode": 443}

END RequestId: 4a06bd2b-cc86-4791-a874-16f8938fc3dd

Report RequestId: 4a06bd2b-cc86-4791-a874-16f8938fc3dd Duration: 0ms Memory: 128MB MemUsage: 7.82MB

START RequestId:4a06bd2b-cc86-4791-a874-16f8938fc3dd

ERROR RequestId:4a06bd2b-cc86-4791-a874-16f8938fc3dd Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python37/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python37/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python37/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python37/lib/python3.7/imp.py\", line 171, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 696, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 677, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 728, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 219, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 11, in \u003cmodule\u003e\n    import requests\nModuleNotFoundError: No module named 'requests'","statusCode":443}

END RequestId:4a06bd2b-cc86-4791-a874-16f8938fc3dd

Report RequestId:4a06bd2b-cc86-4791-a874-16f8938fc3dd Duration:0ms Memory:128MB MemUsage:0.000000MB
